# Generated by Django 6.0.8 on 2026-09-18 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='households.household'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='households.household'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('household', 'name', 'transaction_type'), name='unique_category_per_household'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['household', 'effective_date'], name='finance_tra_househo_74e519_idx'),
        ),
    ]
